[package]
name = "culqi"
version = "0.1.0"
description = "API bindings for the Culqi v2 HTTP API"
authors = ["Willy Aguirre <marti1125@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/marti1125/culqi-rust"
documentation = "https://www.culqi.com/api/"
keywords = ["culqi", "v2", "api"]
categories = ["api-bindings"]

[lib]
name = "culqi"
path = "src/lib.rs"

[dependencies]
hyper = "0.10"
hyper-native-tls = "0.2.2"
serde = "1.0.1"
serde_derive = "1.0.1"
serde_json = "1.0.0"
serde_qs = "0.0.2"
